FROM node:20-bullseye

WORKDIR /app

COPY ./notification-service/kafka.pem kafka.pem
COPY package*.json ./
COPY package-lock.json ./

COPY notification-service ./notification-service
COPY packages ./packages

RUN npm install --workspaces --legacy-peer-deps

RUN npm run build --workspace=notification-service

EXPOSE 3000

CMD ["npm", "start", "--workspace=notification-service"]