FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./

COPY routing-service ./routing-service
COPY packages ./packages

RUN npm install --workspaces --legacy-peer-deps

RUN npm run build --workspace=routing-service

EXPOSE 3000

CMD ["npm", "start", "--workspace=routing-service"]

