export type DeploymentStatusI =
  "CREATED" |
  "INTERNAL_ERROR" |
  "REPO_ANALYSIS_SUCCESS" |
  "REPO_ANALYSIS_FAILED" |
  "BUILD_QUEUE_SUCCESS" |
  "FRONTEND_QUEUE_FAILED" |
  "BACKEND_QUEUE_FAILED" |
  "FRONTEND_PROCESSING" |
  "BACKEND_PROCESSING" |
  "FRONTEND_BUILD_SUCCESS" |
  "BACKEND_BUILD_SUCCESS" |
  "FRONTEND_BUILD_FAILED" |
  "BACKEND_BUILD_FAILED" |
  "BUILD_UNKNOWN_FAILURE" |
  "DEPLOYED" |
  "FAILED";

export enum DeploymentStatus {
  CREATED = "CREATED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  REPO_ANALYSIS_SUCCESS = "REPO_ANALYSIS_SUCCESS",
  REPO_ANALYSIS_FAILED = "REPO_ANALYSIS_FAILED",

  BUILD_QUEUE_SUCCESS = "BUILD_QUEUE_SUCCESS",
  FRONTEND_QUEUE_FAILED = "FRONTEND_QUEUE_FAILED",
  BACKEND_QUEUE_FAILED = "BACKEND_QUEUE_FAILED",

  FRONTEND_PROCESSING = "FRONTEND_PROCESSING",
  BACKEND_PROCESSING = "BACKEND_PROCESSING",

  FRONTEND_BUILD_SUCCESS = "BUILD_SUCCESS",
  BACKEND_BUILD_SUCCESS = "BUILD_SUCCESS",
  FRONTEND_BUILD_FAILED = "FRONTEND_BUILT_FAILED",
  BACKEND_BUILD_FAILED = "BACKEND_BUILT_FAILED",

  BUILD_UNKNOWN_FAILURE = "BUILD_UNKNOWN_FAILURE",
  DEPLOYED = "DEPLOYED",

  FAILED = "FAILED"
}

