export type DeploymentStatusI =
  "CREATED"
  | "INTERNAL_ERROR"
  | "FRONTEND_CLONE_QUEUED"
  | "FRONTEND_CLONING"
  | "FRONTEND_CLONE_FAILED"
  | "FRONTEND_CLONE_SUCCESS"
  | "FRONTEND_BUILD_QUEUED"
  | "FRONTEND_S3_UPLOAD_SUCCESS"
  | "FRONTEND_BUILD_FAILED"
  | "FRONTEND_DEPLOYED"
  | "BACKEND_BUILD_QUEUED"
  | "BACKEND_BUILDING"
  | "BACKEND_BUILD_FAILED"
  | "BACKEND_BUILD_SUCCESS"
  | "BACKEND_DEPLOY_QUEUED"
  | "BACKEND_DEPLOYING"
  | "BACKEND_DEPLOY_FAILED"
  | "BACKEND_DEPLOYED"
  | "DEPLOYMENT_METADATA_RECIEVED"


export enum DeploymentStatus {
  CREATED = "CREATED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  FRONTEND_CLONE_QUEUED = "FRONTEND_CLONE_QUEUED",
  FRONTEND_CLONING = "FRONTEND_CLONING",
  FRONTEND_CLONE_FAILED = "FRONTEND_CLONE_FAILED",
  FRONTEND_CLONE_SUCCESS = "FRONTEND_CLONE_SUCCESS",

  FRONTEND_BUILD_QUEUED = "FRONTEND_BUILD_QUEUED",
  FRONTEND_S3_UPLOAD_SUCCESS = "FRONTEND_S3_UPLOAD_SUCCESS",
  FRONTEND_BUILD_FAILED = "FRONTEND_BUILD_FAILED",
  FRONTEND_DEPLOYED = "FRONTEND_DEPLOYED",

  BACKEND_BUILD_QUEUED = "BACKEND_BUILD_QUEUED",
  BACKEND_BUILDING = "BACKEND_BUILDING",
  BACKEND_BUILD_FAILED = "BACKEND_BUILD_FAILED",
  BACKEND_BUILD_SUCCESS = "BACKEND_BUILD_SUCCESS",

  BACKEND_DEPLOY_QUEUED = "BACKEND_DEPLOY_QUEUED",
  BACKEND_DEPLOYING = "BACKEND_DEPLOYING",
  BACKEND_DEPLOY_FAILED = "BACKEND_DEPLOY_FAILED",
  BACKEND_DEPLOYED = "BACKEND_DEPLOYED",
  
  DEPLOYMENT_METADATA_RECIEVED = "DEPLOYMENT_METADATA_RECIEVED",

  FAILED = "FAILED"
}